### ISSUE TITLE
Create Tesla Token Endpoint Deprecated 

### ISSUE THREAD

**Issue by burchtm** [dburkland/tesla_ios_shortcuts#11]
The current token shortcut errors and it seems to be because the endpoint it uses has been deprecated by Tesla.

**Comment by dburkland** [comment]
Yep they really made a mess with these changes but I have a solution and will be updating the shortcut this week.

Stay tuned,

Dan

**Comment by NeskireDK** [comment]
Who are they? 
Afaik it takes 5 minutes to create a new domain and link it to your application / server in AWS. 
You really should invest in a fixed, paid domain, they are around 8€ auto-renewed every year. 

Also. It should be possible for you to push a new update for the shortcut, with a warning message, ETA and link to this topic. So others can avoid spending 2 hours messing around with this. 

Although I appreciate your work, it is now non-functional due to following your FAQ guide of clearing config.

**Comment by dburkland** [comment]
> Who are they?
> Afaik it takes 5 minutes to create a new domain and link it to your application / server in AWS.
> You really should invest in a fixed, paid domain, they are around 8€ auto-renewed every year.
> 
> Also. It should be possible for you to push a new update for the shortcut, with a warning message, ETA and link to this topic. So others can avoid spending 2 hours messing around with this.
> 
> Although I appreciate your work, it is now non-functional due to following your FAQ guide of clearing config.

They = Tesla. I think you are confusing my AWS Lambda URL and the changes Tesla made.

Tesla retired their previous authentication endpoint so that everybody is now forced to use their v3 system which supports MFA. The new token creation process (which uses oauth2) would be a bit difficult to handle via iOS shortcuts and why I am going to be handling this in AWS Lambda (via python) and updating the "Create Tesla Token" shortcut to simplify updates going forward. 

The personal domain is something I would like to implement in the future however is not really relevant to what Tesla changed here (my URL isn't changing anytime soon). If you ever run into any issues feel free to hit me up on Twitter @dburkland, I am always checking that.

Cheers,

Dan

**Comment by NeskireDK** [comment]
Roger that Dan, thanks for getting back to me. Looking forward to seeing what solution you go
with regarding gathering new tokens, via oauth2. Hopefully something with security and transparency in mind. 

André

**Comment by kdtjlamb** [comment]
Dan.  Thanks for all you do!   This was a curveball that tripped up the Tesla community as a whole.   Telsa was late to the party on oauth and MFA.  That said, Im happy to deal with any short term pains to create a more secure authentication environment.   Love your shortcuts.  Keep up the great work.  Kevin

**Comment by dburkland** [comment]
I have released a new version of the "Create Tesla Token" shortcut that uses an AWS lambda function when creating authentication tokens using Tesla's new process. If you're interested in hosting yourself, I have published the code for both the token and command backends here:

* https://github.com/dburkland/tesla_token_aws_lambda_function
* https://github.com/dburkland/tesla_cmds_aws_lambda_functions

Cheers,

Dan
