### ISSUE TITLE
Storing Tesla Account Email and Password

### ISSUE THREAD

**Issue by oliverwaters** [dburkland/tesla_ios_shortcuts#29]
Hi @dburkland,

I note the Tesla Account Email and Password are requested and stored when using the 'Create Tesla Token' shortcut. If a Token is being retrieved and stored using the Auth for Tesla app, surely this isn't necessary?

Can you clarify why the Tesla Account email and password need to be stored? 

May I suggest reference to why the email and password are requested and stored is also added to the 'How secure are these shortcuts?' section of the README for clarity.

Many thanks.

**Comment by NeskireDK** [comment]
Hi @oliverwaters 
I was a user of these shortcuts before Tesla moved to V3 authentication. Prior to that update, the shortcuts would store settings along with authentication into your icloud drive (which is as secure as can be, while still readable by any app / shortcut / user that asks for permissions). These stored authentication credentials were actually used to autofill the monthly generate authentication token. However, since switching to using "Auth for Tesla" app to handle V3 auth, that feature stopped working. 
My guess is that he never updated the code to remove the storage of credentials, as he still intended to restore original behavior, just never did. 

Security wise, you should be more interested in the fact that a AWS service somwhere, with closed source code is receiving your authtoken, and can do whatever it wants to your car for up to 45 days at a time :) I, personally, ignore this fear. I have yet to see a single unauthorized request / wake to my car during the last 10 months using these shortcuts. I track my car and it sleeps 90% of the time, driving around 4% of the time, standby 1%, charges 5% of the time. If my Tesla was being data mined and crawled, I would see it in those stats, like I do with most other tesla integrations.

**Comment by oliverwaters** [comment]
Thanks for the reply @NeskireDK. Makes sense.

**Comment by dburkland** [comment]
The shortcuts still leverage the stored credentials however generation of the auth tokens are no longer done via shortcuts (v3 made a mess of this and thus why I use a helper app for this piece). The password that is stored locally is only used by the "Start Remote Drive" shortcut as it is a required parameter. If you do not use this shortcut then you can simply enter a garbage password into the prompt.

As far as the code used in the AWS Lambda functions, they are not closed source as I have publicly shared the code here -> https://github.com/dburkland/tesla_token_aws_lambda_function.

Cheers,

Dan
