### ISSUE TITLE
Close Trunk not working

### ISSUE THREAD

**Issue by Marcoqwerty78** [dburkland/tesla_ios_shortcuts#7]
If you download the the Close Trunk shortcut directly from https://www.icloud.com/shortcuts/b6276635a8de482f8c0cd7674de3b8a0 (Shortcut downloader), the Close Trunk shortcut looks empty.

**Comment by dburkland** [comment]
Did you download the "Open Trunk" shortcut before downloading the "Close Trunk" shortcut? If not I would recommend doing that first then downloading the "Close Trunk" shortcut. The "Close Trunk" shortcut is just an alias for the "Open Trunk" shortcut since they call the same API on the Tesla side. 

Cheers,

Dan

**Comment by dburkland** [comment]
@Marcoqwerty78 I updated the README to include additional details about how to handle this particular issue underneath the "Create Tesla Token" bullet. Feel free to re-open or message me on Twitter if you continue to experience issues.

Cheers,

Dan
